services:
  application:
    build: .
    ports:
      - 8000:8000
      - 8080:8080
      - 50051:50051
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=orders
      - WEB_SERVER_PORT=:8000
      - GRPC_SERVER_PORT=50051
      - GRAPHQL_SERVER_PORT=8080
    restart: always

  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
